language: java
dist: trusty

before_install:
  - rm -rf $HOME/.m2/repository/org/examples
  - cp .travis/travis_settings.xml $HOME/.m2/settings.xml

script:
  - mvn install

before_cache:
  - rm -rf $HOME/.m2/repository/org/examples
cache:
  directories:
    - "$HOME/.m2/repository"

deploy:
  provider: script
  script: "mvn deploy -DskipTests"
  on:
    branch: master

after_deploy:
  - chmod u+x .travis/travis_downstream_deploy.sh
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then .travis/travis_downstream_deploy.sh; fi
